### ISSUE TITLE
About the 2D segmentor

### ISSUE THREAD

**Issue by monoavatar** [manymuch/CAMA#1]
Hi, thanks for your nice work!

I'm interested in the 2D segmentor that you used in CAMA. The paper mentions that you use Mask2Former to get road and lane segmentation masks. May I ask which specific model & results are ued in CAMA (Mapillary Vistas Model and Semantic Segmentation results? or the Panoptic Segmentation results?)

Looking forward to your reply!

**Comment by manymuch** [comment]
Thanks for the interets, Mask2Former trained on Mapillary is good, no need for panoptic segmentation.
