### ISSUE TITLE
when will release annos for v1.0-trainval？

### ISSUE THREAD

**Issue by swc-17** [manymuch/CAMA#3]
Hi, 
   Interesting work! I wonder when will you release map annotations for v1.0-trainval？

**Comment by swc-17** [comment]
It seems that annotations for v1.0-test is also not complete.

**Comment by manymuch** [comment]
Sorry for the extremely late reply, we have uploaded the better annotations versioned 2.0 you can see in [readme](https://drive.google.com/file/d/1B-C6XyfnxfmHaKcp6U2Hygy-TpTmtQce/view?usp=sharing).
